# oml server settings
server:
  port: 55411

# oml-cli parameter defaults
defaults:
  export: -o build/owl
  reason: -o build/owl -t -u false
  render: -m src/model/md -b build/web -c src/model/oml/fireforce6.github.io/mission-control/bundle.oml
